env_name: swarm-1d
logging: offline
device: cuda:0
entity: user
logdir: 
run_id: 20220805
dynamics_ckpt: 
policy_ckpt:
exec_type: train

model:
  mu_dim: 400 
  delta: 0.01
  control_std: 0.25
  constraint_lipschitz: 0.25
  max_entropy_ratio: # pct of max entropy
  barrier_lambda: 10.0
  dynamics_type: known
  num_agents: 1
  reward_type: current_mu

  dynamics:
    beta: 1.0             
    ensemble_nets: 10
    hidden_dims: [16, 16]
    lr: 0.0001
    weight_decay: 0.0005
    dynamics_epochs: 10_000
    buffer_size: 10
    reset_params_every_episode: False
    batch_size: 16
    holdout: 0.9    # 90% train, 10% validation

  solver:
    policy:
      lr: 0.0001
      hidden_dims: [64, 64]
      weight_decay: 0.0005
    reset_params_every_episode: False
    patience: 10
    action_std: 0.5
    polar: false
    gmm: false

training:
  n_episodes: 1_000
  horizon: 100
  policy_epochs: 20_000
  warmup_steps: 0
  n_repeats: 1