env_name: swarm-1d-linear
logging: offline
device: cuda:0
entity: user
logdir: 
run_id: 20231006
dynamics_ckpt: 
policy_ckpt:
exec_type: train

model:
  mu_dim: 100 
  control_std: 1.
  constraint_lipschitz: 0.000001
  max_entropy_ratio: 0.95
  barrier_lambda: 15.0
  dynamics_type: unknown
  num_agents: 1
  reward_type: current_mu

  dynamics:
    beta: 1.0             
    ensemble_nets: 10
    hidden_dims: [16, 16]
    lr: 0.005
    weight_decay: 0.0005
    dynamics_epochs: 10_000
    buffer_size: 10_000
    reset_params_every_episode: True
    batch_size: 8
    holdout: 0.9    # 90% train, 10% validation
    exclude_mu: True
    adversarial_epsilon:

  solver:
    policy:
      lr: 0.005
      hidden_dims: [16, 16]
      weight_decay: 0.0005
    reset_params_every_episode: True
    patience: 1
    exploration_decay:
    polar: false
    gmm: false

training:
  n_episodes: 1_000
  horizon: 100
  policy_epochs: 50_000
  warmup_steps: 0
  n_repeats: 1